# Generated by Django 5.2 on 2025-04-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendedlocation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendedlocation',
            name='vibes',
            field=models.ManyToManyField(related_name='recommended_locations', to='api.vibe'),
        ),
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
